name: Shard CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  LintAndTest:
    strategy:
      fail-fast: false
      matrix:
        image_tag:
          - 0.34.0-alpine
          - 0.35.1-alpine
          - latest-alpine
        experimental: [false]
        include:
          - image_tag: nightly-alpine
            experimental: true

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.image_tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Check format
        run: crystal tool format --check

      - name: Set up Crystal cache
        uses: actions/cache@v2
        id: crystal-cache
        with:
          path: |
            ~/.cache/crystal
            bin/ameba
            lib
          key: ${{ runner.os }}-crystal-${{ matrix.image_tag }}-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-crystal-${{ matrix.image_tag }}

      - name: Install shards
        if: steps.crystal-cache.outputs.cache-hit != 'true'
        run: shards check || shards install

      - name: Crystal Ameba Linter
        run: ./bin/ameba

      - name: Run tests
        run: crystal spec
